# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rules.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rules.proto',
  package='tutorial',
  serialized_pb=_b('\n\x0brules.proto\x12\x08tutorial\"\"\n\x05Lrule\x12\x0e\n\x06\x62ranch\x18\x01 \x02(\t\x12\t\n\x01r\x18\x02 \x02(\t\"4\n\x04Line\x12\x0c\n\x04lnum\x18\x01 \x02(\x05\x12\x1e\n\x05lrule\x18\x02 \x03(\x0b\x32\x0f.tutorial.Lrule\"3\n\x04Rule\x12\r\n\x05\x66name\x18\x01 \x02(\t\x12\x1c\n\x04line\x18\x02 \x03(\x0b\x32\x0e.tutorial.Line\"&\n\x05Rules\x12\x1d\n\x05rules\x18\x01 \x03(\x0b\x32\x0e.tutorial.Rule')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LRULE = _descriptor.Descriptor(
  name='Lrule',
  full_name='tutorial.Lrule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='branch', full_name='tutorial.Lrule.branch', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='r', full_name='tutorial.Lrule.r', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=59,
)


_LINE = _descriptor.Descriptor(
  name='Line',
  full_name='tutorial.Line',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lnum', full_name='tutorial.Line.lnum', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lrule', full_name='tutorial.Line.lrule', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=113,
)


_RULE = _descriptor.Descriptor(
  name='Rule',
  full_name='tutorial.Rule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fname', full_name='tutorial.Rule.fname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='line', full_name='tutorial.Rule.line', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=166,
)


_RULES = _descriptor.Descriptor(
  name='Rules',
  full_name='tutorial.Rules',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rules', full_name='tutorial.Rules.rules', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=206,
)

_LINE.fields_by_name['lrule'].message_type = _LRULE
_RULE.fields_by_name['line'].message_type = _LINE
_RULES.fields_by_name['rules'].message_type = _RULE
DESCRIPTOR.message_types_by_name['Lrule'] = _LRULE
DESCRIPTOR.message_types_by_name['Line'] = _LINE
DESCRIPTOR.message_types_by_name['Rule'] = _RULE
DESCRIPTOR.message_types_by_name['Rules'] = _RULES

Lrule = _reflection.GeneratedProtocolMessageType('Lrule', (_message.Message,), dict(
  DESCRIPTOR = _LRULE,
  __module__ = 'rules_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Lrule)
  ))
_sym_db.RegisterMessage(Lrule)

Line = _reflection.GeneratedProtocolMessageType('Line', (_message.Message,), dict(
  DESCRIPTOR = _LINE,
  __module__ = 'rules_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Line)
  ))
_sym_db.RegisterMessage(Line)

Rule = _reflection.GeneratedProtocolMessageType('Rule', (_message.Message,), dict(
  DESCRIPTOR = _RULE,
  __module__ = 'rules_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Rule)
  ))
_sym_db.RegisterMessage(Rule)

Rules = _reflection.GeneratedProtocolMessageType('Rules', (_message.Message,), dict(
  DESCRIPTOR = _RULES,
  __module__ = 'rules_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Rules)
  ))
_sym_db.RegisterMessage(Rules)


# @@protoc_insertion_point(module_scope)
